### ISSUE TITLE
Password protected access

### ISSUE THREAD

**Issue by bigginhill** [vitorbaptista/shellshare#34]
Hi there,

I've set a custom room address & password, hoping that this would password protect the page.

However I am able to access the page from other machines without entering a password? Is this the intended functionality? Password protection would be fantastic.

Either way, this is a fantastic tool.
Biggin

**Comment by vitorbaptista** [comment]
@bigginhill Sorry for the delay in answering. Yes, this is the intended functionality: the passwords are just to avoid someone else from publishing to the same room. However, as there's no list of rooms anywhere (by design), the only way for someone to get into your room is by you (or someone else) telling her the URL.

I'd think this should be enough for most cases. If not, please reopen this issue explain better what you're trying to do. I'm happy to reconsider.
