### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol when setting up a new server

### ISSUE THREAD

**Issue by amosbird** [vitorbaptista/shellshare#51]
I followed the `README.md` exactly and after executing `./public/bin/shellshare --server localhost:3000` I got
```
[amos@VM_31_14_centos shellshare]$ Unhandled exception in thread started by <function stream_file at 0x22a3320>
                                                                                                               Traceback (most recent call last):
                            File "./public/bin/shellshare", line 90, in stream_file
                                                                                       success = post(conn, url, encoded_str, room, password)
                        File "./public/bin/shellshare", line 71, in post
                                                                            raise e
                                                                                   ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:765)
```

It's a centos 7.2 server.
[amos@VM_31_14_centos shellshare]$

**Comment by vitorbaptista** [comment]
Thanks for the report. The issue is that we're always using HTTPS, which breaks HTTP servers. We'll have to change the `shellshare` binary to support both HTTP and HTTPS. Meanwhile, if you want to try locally, you can change the line at https://github.com/vitorbaptista/shellshare/blob/5394707a007ae8359a7cc9747dbc33276a4757f5/public/bin/shellshare#L78 from `conn = httplib.HTTPSConnection(url)` to `conn = httplib.HTTPConnection(url)`. Note that this mean the `shellshare` binary won't work with HTTPS (e.g. with the main server).

**Comment by vitorbaptista** [comment]
@amosbird I just fixed the bug and released a new version. Please, reopen this issue if it doesn't fix your problem. Thanks for the report!

**Comment by amosbird** [comment]
thanks! it works as expected now.
